### ISSUE TITLE
Instances will occasionally not pause correctly

### ISSUE THREAD

**Issue by DraconicCode** [woofdoggo/resetti#6]
Using the latest full release (0.3.1 iirc), instances occasionally do not pause on world load, and are shown as Generating in resetti. To fix, I have to select the instance (due to my settings, manually select it from the taskbar), reset like I would for single instance, then reset the instance in resetti.

**Comment by sathya-pramodh** [comment]
Uhh could we probably add a buffer to the pausing? Like maybe only pause it after like 10% of world load or something....Could handle all race conditions by what I've seen...

**Comment by woofdoggo** [comment]
Waiting for the preview to reach a certain percentage isn't a bad idea. I haven't experienced any issues with instances not pausing on `main` where there is a 10 millisecond delay between entering preview and sending the pause inputs, although I have my `loading_screen` FPS limit in SleepBackground set to 30.

I'd be willing to do some tweaks to the pausing logic to make it more consistent if you are experiencing issues on the latest commit. If there's issues with instances not pausing when finishing world generation, though, that would be a bit more complicated (since right now the 10 millisecond pause wait is synchronous and blocks handling events from other instances.)

**Comment by woofdoggo** [comment]
Changed preview pausing to happen at 5% generation in 828cf50.

**Comment by sathya-pramodh** [comment]
Cool :DD I'll test it out a little bit and let you know how it turns out.

**Comment by woofdoggo** [comment]
This should be fixed in [0.4.0-beta2](https://github.com/woofdoggo/resetti/releases/tag/v0.4.0-beta2).
